-- Sample data for local development

-- Insert users
INSERT INTO public.users (email, first_name, last_name, phone, role, status) VALUES
('chonker@example.com', 'Chonky', 'Cat', '555-0001', 'customer', 'active'),
('fluffy@example.com', 'Fluffy', 'Kitten', '555-0002', 'customer', 'active'),
('admin@example.com', 'Admin', 'User', '555-9999', 'admin', 'active');

-- Insert products from CSV data
INSERT INTO public.products (sku, name, description, ingredients, image_url, category, price, qty, low_stock_threshold, active) VALUES
('DRY-CK-001', 'Chonky Kibble – Original Chicken', 'Our flagship dry food. Oven-roasted chicken in every crunchie, taurine-fortified and sized for the discerning chonk. High protein, zero apologies. The one that started it all.', 'Chicken, Chicken Fat, Taurine, Dried Beet Pulp, Brewers Rice, Corn Starch, Fish Oil, Vitamin E Supplement, Zinc Sulfate', 'img/dry-ck-001.jpg', 'Dry Food', 22.99, 200, 25, true),
('DRY-CK-002', 'Chonky Kibble – Salmon & Kelp', 'Wild-caught salmon paired with nutrient-dense kelp for a deep-sea crunch your couch-bound predator absolutely does not deserve but will receive anyway. Omega-3 enriched for a coat that gleams with unearned confidence.', 'Salmon, Salmon Oil, Kelp, Brewers Rice, Pea Protein, Taurine, Vitamin E Supplement, Omega-3 Fatty Acids, Zinc Sulfate', 'img/dry-ck-002.jpg', 'Dry Food', 23.99, 175, 25, true),
('DRY-CP-001', 'Chonk+ Kibble – Buttered Turkey with Gravy Clusters', 'Rich butter-basted turkey kibble with pockets of solidified gravy baked right in. Yes there is glucosamine in here somewhere. No that is not why your cat will eat it. Formulated for cats aged 7+ who have fully given up on cardio.', 'Turkey, Butter, Beef Dripping, Rendered Turkey Fat, Dried Gravy Powder, Corn Starch, Taurine, Glucosamine Hydrochloride, Chondroitin Sulfate', 'img/dry-cp-001.jpg', 'Dry Food', 31.99, 120, 20, true),
('DRY-CP-002', 'Chonk+ Kibble – Gravy-Soaked Double Chicken with Beef Drippings', 'Two kinds of chicken — roasted AND fried — bathed in rendered beef drippings and pressure-sealed into every kibble. Veterinarian-disapproved. Cat-adored. The Chonk+ line is about thriving, not surviving. Your cat did not come to this earth to eat diet food and you know it.', 'Roasted Chicken, Fried Chicken, Beef Drippings, Rendered Chicken Fat, Chicken Liver, Corn Starch, Taurine, Brewers Yeast, Vitamin E Supplement', 'img/dry-cp-002.jpg', 'Dry Food', 34.99, 90, 20, true),
('WET-001', 'Rustic Sparrow Pâté with Roasted Crickets', 'Free-range garden sparrow slow-blended into a silky pâté, crowned with whole roasted crickets for a sustainable crunch your cat will pick around deliberately. Très chic. Very chonk.', 'Sparrow, Sparrow Broth, Roasted Cricket, Chicken Fat, Corn Starch, Thyme, Taurine, Guar Gum, Vitamin E Supplement', 'img/wet-001.jpg', 'Wet Food', 4.49, 300, 40, true),
('WET-002', 'Minced Squirrel in Beef Broth', 'Tender grey squirrel hand-minced and simmered in a rich beef broth with heirloom carrot ribbons. The backyard, in a tin. Your cat will act like they caught it themselves.', 'Squirrel, Beef Broth, Carrot, Beef Fat, Corn Starch, Taurine, Guar Gum, Potassium Chloride, Vitamin E Supplement', 'img/wet-002.jpg', 'Wet Food', 4.49, 280, 40, true),
('WET-003', 'Cornish Pigeon Confit with Giblet Gravy', 'Heritage-breed pigeon slow-cooked confit-style until fall-apart tender, served in its own rich giblet gravy. A dish your cat will inhale in 11 seconds flat.', 'Pigeon, Pigeon Giblets, Pigeon Broth, Chicken Fat, Corn Starch, Taurine, Guar Gum, Vitamin E Supplement, Zinc Sulfate', 'img/wet-003.jpg', 'Wet Food', 4.99, 260, 40, true),
('WET-004', 'Garter Snake Terrine with Bacon Chunks', 'Delicately deboned garter snake pressed into a smooth terrine studded with generous bacon chunks and a hint of smoked paprika. Polarising at dinner parties. Beloved at breakfast. The bacon was not necessary. We added it anyway.', 'Garter Snake, Snake Broth, Bacon, Chicken Fat, Smoked Paprika, Corn Starch, Taurine, Guar Gum, Potassium Chloride', 'img/wet-004.jpg', 'Wet Food', 4.99, 220, 40, true),
('WET-005', 'Chipmunk Fricassée with Acorn Butter Sauce', 'Braised chipmunk in a classic fricassée with pearl onions, green beans, and a velvety acorn butter sauce. French technique. Canadian chipmunk. Universal approval.', 'Chipmunk, Chipmunk Broth, Acorn Butter, Pearl Onion, Green Bean, Chicken Fat, Corn Starch, Taurine, Guar Gum', 'img/wet-005.jpg', 'Wet Food', 5.29, 190, 35, true),
('WET-006', 'Field Mouse Bourguignon', 'Slow-braised field mouse in a robust Burgundy-style reduction with lardons, button mushrooms, and baby carrots. Oui oui. Nom nom.', 'Field Mouse, Mouse Broth, Bacon Lardon, Button Mushroom, Carrot, Red Wine Reduction, Chicken Fat, Corn Starch, Taurine', 'img/wet-006.jpg', 'Wet Food', 5.29, 210, 35, true),
('WET-007', 'Song Thrush & Worm Medley Pâté', 'Earthy song thrush blended with earthworm protein into a deeply savoury pâté. Rich in iron. Richer in personality. Not for the faint of heart — but your cat is not faint of heart.', 'Song Thrush, Earthworm Protein, Thrush Broth, Chicken Fat, Corn Starch, Taurine, Guar Gum, Iron Proteinate, Vitamin E Supplement', 'img/wet-007.jpg', 'Wet Food', 4.79, 240, 40, true),
('WET-008', 'Baby Rabbit Stew with Tarragon & Marrow', 'Meltingly tender rabbit braised with fresh tarragon and bone marrow for an unctuous, collagen-rich broth. The Sunday roast your cat has been silently judging you for not making.', 'Rabbit, Rabbit Bone Marrow, Rabbit Broth, Tarragon, Chicken Fat, Corn Starch, Taurine, Guar Gum, Potassium Chloride', 'img/wet-008.jpg', 'Wet Food', 5.49, 170, 30, true),
('WET-009', 'Braised Shrew with Quail Egg & Caper Gravy', 'Common shrew slow-braised until tender and packed in a rich quail egg and caper gravy. Briny. Decadent. Deeply suspicious. A tin that raises questions your vet will not want to answer.', 'Shrew, Shrew Broth, Quail Egg, Capers, Chicken Fat, Corn Starch, Taurine, Guar Gum, Potassium Chloride', 'img/wet-009.jpg', 'Wet Food', 5.49, 6, 30, true),
('WET-010', 'Roasted Finch Pâté with Sun-Dried Cricket Crust', 'Garden finch roasted and blended to a smooth pâté, encrusted with sun-dried crickets for an artisanal crunch. High in sustainable protein.', 'Finch, Finch Broth, Sun-Dried Cricket, Chicken Fat, Corn Starch, Taurine, Guar Gum, Vitamin E Supplement, Zinc Sulfate', 'img/wet-010.jpg', 'Wet Food', 5.29, 200, 35, true),
('SNK-001', 'Freeze-Dried Salmon Skin Crisps', 'Wild salmon skins freeze-dried at peak freshness into an ultra-crunchy crisp. One ingredient. Infinite chaos. Shake the bag from across the house and watch a 14 lb cat achieve liftoff.', 'Salmon Skin, Salmon Oil', 'img/snk-001.jpg', 'Snacks', 11.99, 150, 20, true),
('SNK-002', 'Chonky Chonk Pill Pockets – Chicken Flavour', 'Soft, mouldable chicken-flavoured pouches for hiding medication inside. Works great until your cat eats around the pill with surgical precision and stares at you.', 'Chicken, Chicken Liver, Gelatin, Glycerin, Corn Starch, Natural Chicken Flavour, Brewers Yeast, Vitamin E Supplement, Sorbic Acid', 'img/snk-002.jpg', 'Snacks', 13.99, 130, 20, true),
('SNK-003', 'Lickable Salmon & Tuna Tubes (6-pack)', 'Six single-serve squeeze tubes of creamy salmon and tuna blended into a smooth purée. High in moisture. Excellent for bonding, bribery, and basic veterinary compliance. Will be consumed in four seconds.', 'Salmon, Tuna, Fish Broth, Sunflower Seed Oil, Xanthan Gum, Taurine, Potassium Chloride, Vitamin E Supplement', 'img/snk-003.jpg', 'Snacks', 9.99, 220, 30, true),
('SNK-004', 'Crunchy Pork & Catnip Nuggets', 'Minced pork shaped into paw-sized nuggets and tumbled in premium dried catnip. Deeply irresponsible. Spiritually chaotic. Your cat has been waiting their whole life for this without knowing it.', 'Pork, Pork Fat, Dried Catnip, Brewers Yeast, Corn Starch, Taurine, Vitamin E Supplement', 'img/snk-004.jpg', 'Snacks', 10.99, 9, 15, true),
('SNK-005', 'Chewable Gizzard Dental Chews', 'Chewy chicken gizzard strips with an abrasive texture designed to support dental health. Your cat will pretend to hate them while finishing the bag in one sitting. The only product on this site your vet might cautiously approve of.', 'Chicken Gizzard, Chicken Fat, Glycerin, Gelatin, Corn Starch, Taurine, Vitamin E Supplement, Zinc Sulfate', 'img/snk-005.jpg', 'Snacks', 12.99, 110, 20, true),
('SNK-006', 'Duck Liver Mousse Bites', 'Airy, melt-in-mouth duck liver mousse set into bite-sized cubes and freeze-dried. The amuse-bouche your cat deserves after a long day of napping on your laptop.', 'Duck Liver, Duck Fat, Chicken Broth, Corn Starch, Taurine, Vitamin E Supplement, Zinc Sulfate, Iron Proteinate', 'img/snk-006.jpg', 'Snacks', 14.99, 75, 15, true);

-- Insert promotions
INSERT INTO public.promotions (code, discount_type, discount_value, active) VALUES
('WELCOME10', 'percentage', 10.00, true),
('SUMMER20', 'percentage', 20.00, true),
('FREESHIP', 'fixed', 5.00, true);
